name: holiday_calendar
description: "Bangladesh public holiday Calendar 2025"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  #all packages
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  table_calendar: ^3.2.0
  flutter_riverpod: ^3.0.3
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/json/

  fonts:
    - family: Watford
      fonts:
        - asset: assets/fonts/watfard-regular.ttf
          style: normal

